/**
 * Friendly names for the types generated from docs/openapi.yaml.
 * Regenerate the source with `npm run generate`; never edit src/generated by hand.
 */
import type { components, operations } from "./generated/openapi.js";

type Schemas = components["schemas"];
type Query<Op extends keyof operations> = NonNullable<operations[Op]["parameters"]["query"]>;

// ---- Scrape ---------------------------------------------------------------
export type ScrapeRequest = Schemas["ScrapeRequest"];
export type ScrapeEnvelope = Schemas["ScrapeEnvelope"];
export type ScrapeAction = Schemas["ScrapeAction"];
export type ScrapeExtract = Schemas["ScrapeExtract"];
export type ScrapeScreenshot = Schemas["ScrapeScreenshot"];
export type ScrapeNetworkResponse = Schemas["ScrapeNetworkResponse"];
export type ScrapeDiagnostics = Schemas["ScrapeDiagnostics"];
export type AIExtract = Schemas["AIExtract"];
export type NetworkCapture = Schemas["NetworkCapture"];
export type ResponseFormat = NonNullable<ScrapeRequest["response_format"]>;

// ---- Batch ----------------------------------------------------------------
export type BatchCreateRequest = Schemas["BatchCreateRequest"];
export type BatchScrapeParams = Schemas["BatchScrapeParams"];
export type BatchItem = Schemas["BatchItem"];
export type BatchJob = Schemas["BatchJob"];
export type BatchJobStatus = Schemas["BatchJobStatus"];
export type BatchItemStatus = Schemas["BatchItemStatus"];
export type BatchJobProgress = Schemas["BatchJobProgress"];
export type BatchJobList = Schemas["BatchJobList"];
export type BatchRetryResponse = Schemas["BatchRetryResponse"];
export type BatchAppendResponse = Schemas["BatchAppendResponse"];
export type BatchAppendRequest = NonNullable<operations["batchAppend"]["requestBody"]>["content"]["application/json"];
export type BatchResultLine = Schemas["BatchResultLine"];
export type BatchResultBody = Schemas["BatchResultBody"];
export type BatchResultError = Schemas["BatchResultError"];
export type BatchListParams = Query<"batchList">;
export type BatchResultsParams = Query<"batchResults">;

// ---- Sessions -------------------------------------------------------------
export type Session = Schemas["Session"];
export type SessionCreateRequest = Schemas["SessionCreateRequest"];
export type SessionList = Schemas["SessionList"];
export type SessionEngine = Schemas["SessionEngine"];
export type SessionContextDump = Schemas["SessionContextDump"];
export type SessionCookie = Schemas["SessionCookie"];
export type SessionListParams = Query<"sessionsList">;

// ---- Requests -------------------------------------------------------------
export type RequestLogEntry = Schemas["RequestLogEntry"];
export type RequestLogPage = Schemas["RequestLogPage"];
export type RequestLogPageInfo = Schemas["RequestLogPageInfo"];
export type RequestListParams = Query<"requestsList">;

// ---- Usage ----------------------------------------------------------------
export type UsageMetric = Schemas["UsageMetric"];
export type UsageBreakdown = Schemas["UsageBreakdown"];
export type UsageByKey = Schemas["UsageByKey"];
export type UsageSummary = Schemas["UsageSummary"];
export type UsageReconciliation = Schemas["UsageReconciliation"];
export type UsageParams = Query<"usageGet">;
export type UsageReconciliationParams = Query<"usageReconciliation">;

// ---- Browser (coming soon) -------------------------------------------------
export type BrowserTokenRequest = NonNullable<
  NonNullable<operations["browserToken"]["requestBody"]>["content"]["application/json"]
>;
export type BrowserToken = operations["browserToken"]["responses"][200]["content"]["application/json"];
export type BrowserConnectParams = Query<"browserConnect">;

// ---- Errors ---------------------------------------------------------------
export type Problem = Schemas["Problem"];
export type ProblemDiagnostics = Schemas["ProblemDiagnostics"];

/**
 * Every documented error code. Taken from the spec's `x-spicrawl-errors` catalogue rather than
 * the generated `ErrorCode` enum, which is malformed in the current spec (see CHANGELOG).
 * The trailing `(string & {})` keeps codes added server-side assignable without losing
 * autocomplete.
 */
export const ERROR_CODES = [
  "ERR::AUTH::MISSING_KEY",
  "ERR::AUTH::INVALID_KEY",
  "ERR::AUTH::REVOKED_KEY",
  "ERR::AUTH::EXPIRED_KEY",
  "ERR::AUTH::FORBIDDEN",
  "ERR::AUTH::INSUFFICIENT_SCOPE",
  "ERR::AUTH::INVALID_TOKEN",
  "ERR::AUTH::INVALID_CREDENTIALS",
  "ERR::AUTH::ENGINE_NOT_ENTITLED",
  "ERR::REQUEST::INVALID",
  "ERR::REQUEST::MISSING_PARAMETER",
  "ERR::REQUEST::INVALID_PARAMETER",
  "ERR::REQUEST::INCOMPATIBLE_FLAGS",
  "ERR::REQUEST::NOT_FOUND",
  "ERR::REQUEST::BEYOND_RETENTION",
  "ERR::REQUEST::CONFLICT",
  "ERR::REQUEST::PAYLOAD_TOO_LARGE",
  "ERR::REQUEST::CAPABILITY_UNSUPPORTED",
  "ERR::SECURITY::SSRF_BLOCKED",
  "ERR::SECURITY::URL_BLOCKED",
  "ERR::SECURITY::INVALID_URL",
  "ERR::SESSION::NOT_FOUND",
  "ERR::SESSION::EXPIRED",
  "ERR::SESSION::RELEASED",
  "ERR::SESSION::BUSY",
  "ERR::SESSION::STATE_CORRUPT",
  "ERR::LIMIT::RATE_LIMITED",
  "ERR::LIMIT::CONCURRENCY_EXCEEDED",
  "ERR::LIMIT::QUOTA_EXCEEDED",
  "ERR::LIMIT::MAX_COST_EXCEEDED",
  "ERR::LIMIT::SESSIONS_EXCEEDED",
  "ERR::UPSTREAM::TIMEOUT",
  "ERR::UPSTREAM::DNS_FAILED",
  "ERR::UPSTREAM::TLS_FAILED",
  "ERR::UPSTREAM::CONNECTION_RESET",
  "ERR::UPSTREAM::TOO_MANY_REDIRECTS",
  "ERR::UPSTREAM::ERROR",
  "ERR::UPSTREAM::CHALLENGE",
  "ERR::PROXY::EXHAUSTED",
  "ERR::PROXY::UNREACHABLE",
  "ERR::PROXY::AUTH_FAILED",
  "ERR::PROXY::RATE_LIMITED",
  "ERR::ENGINE::RENDER_FAILED",
  "ERR::ENGINE::UNAVAILABLE",
  "ERR::EXTRACT::FAILED",
  "ERR::EXTRACT::INVALID_RULES",
  "ERR::INTERNAL::ERROR",
  "ERR::INTERNAL::UNAVAILABLE",
] as const;

export type KnownErrorCode = (typeof ERROR_CODES)[number];
// eslint-disable-next-line @typescript-eslint/ban-types
export type ErrorCode = KnownErrorCode | (string & {});

/** Metadata read from response headers, attached to every result. */
export interface ResponseMeta {
  /** The platform's HTTP status for this response. */
  status: number;
  /** `X-Request-Id`; pass to `spicrawl.requests.get()` for the full trace. */
  requestId: string | null;
  /** `X-Credits-Charged`: what this call actually billed. */
  creditsCharged: number | null;
  /**
   * `X-Credits-Remaining`: the organization's monthly allowance left after this call's charge
   * (a batch submit, append or retry: after its hold), in whole credits rounded down. `null` when
   * the org has no ceiling, on a refusal before the credit check, or when the counter could not be read.
   */
  creditsRemaining: number | null;
  /** `X-Request-Cost`: what the tier that ran would have cost. */
  requestCost: number | null;
  rateLimit: { limit: number | null; remaining: number | null; reset: number | null };
  /** `X-Engine`: engine that produced a scrape. */
  engine: string | null;
  /** `Cache-State`: hit, miss or bypass. */
  cacheState: "hit" | "miss" | "bypass" | null;
  /** `X-Target-Status`: the TARGET site's status on a scrape (not the platform's). */
  targetStatus: number | null;
  /** `X-Warning` values, `CODE: message`. */
  warnings: string[];
  /** All raw response headers. */
  headers: Headers;
}

/** A result with its response metadata on a non-enumerable `_meta` property. */
export type WithMeta<T> = T & { readonly _meta: ResponseMeta };
